index:
    path: /
    controller: Nbe\PhpBlocks\Infrastructure\HttpApi\Controller\RootController::indexAction

transactions.new:
    path: /transactions/new
    controller: Nbe\PhpBlocks\Infrastructure\HttpApi\Controller\TransactionController::postAction

mine:
    path: /mine
    controller: Nbe\PhpBlocks\Infrastructure\HttpApi\Controller\MineController::getAction

chain:
    path: /chain
    controller: Nbe\PhpBlocks\Infrastructure\HttpApi\Controller\BlockchainController::getAction